version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
    volumes:
      - './uptime-kuma:/app/data'
    environment:
      PORT: 3001
      VIRTUAL_HOST: ${UPTIME_DOMAIN}
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}
